"""Common configuration constants
"""
PROJECTNAME = 'scoreboard.visualization'

ADD_PERMISSIONS = {
    'ScoreboardVisualization':
        'scoreboard.visualization: Add ScoreboardVisualization',
}

from zope.i18nmessageid.message import MessageFactory
_ = MessageFactory('scoreboard')

# This list is used by country_profile chart and can be customized within
# ZMI > portal_properties > scoreboard_properties
EU = {
    "BE": "Belgium",
    "BG": "Bulgaria",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DE": "Germany",
    "EE": "Estonia",
    "IE": "Ireland",
    "EL": "Greece",
    "ES": "Spain",
    "FR": "France",
    "IT": "Italy",
    "CY": "Cyprus",
    "LV": "Latvia",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "HU": "Hungary",
    "MT": "Malta",
    "NL": "Netherlands",
    "AT": "Austria",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "FI": "Finland",
    "SE": "Sweden",
    "UK": "United Kingdom"
}

# This list is used by country_profile chart and can be customized within
# ZMI > portal_properties > scoreboard_properties
WHITELIST = [
    {'indicator': 'AAAA_cov', 'breakdown': '1M_websites', 'unit-measure': 'pc_websites'},
    {'indicator': 'actspeed', 'breakdown': 'cable', 'unit-measure': 'pc_nomspeed'},
    {'indicator': 'e_broad', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_crman', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_inv', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_rfid', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'P_EMPMD', 'breakdown': 'ent_all_xfin', 'unit-measure': 'PC_EMP'},
    {'indicator': 'e_ra', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'E_WEB', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_igov', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_igovrt', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_igov2pr', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'P_IUSE', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_emp'},
    {'indicator': 'E_ITSP2', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'E_ITSPVAC2', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_pmd', 'breakdown': 'ent_all_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_sisorp', 'breakdown': 'ent_l_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_ade', 'breakdown': 'ent_l_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_sisc', 'breakdown': 'ent_l_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_empmd_gt20', 'breakdown': 'ent_l_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'E_ERP1', 'breakdown': 'ent_l_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_eturn', 'breakdown': 'ent_l_xfin', 'unit-measure': 'pc_turn'},
    {'indicator': 'e_ebuy', 'breakdown': 'ent_l_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_esell', 'breakdown': 'ent_l_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_sisorp', 'breakdown': 'ent_sm_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_ade', 'breakdown': 'ent_sm_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_sisc', 'breakdown': 'ent_sm_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_empmd_gt20', 'breakdown': 'ent_sm_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'E_ERP1', 'breakdown': 'ent_sm_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_eturn', 'breakdown': 'ent_sm_xfin', 'unit-measure': 'pc_turn'},
    {'indicator': 'e_ebuy', 'breakdown': 'ent_sm_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'e_esell', 'breakdown': 'ent_sm_xfin', 'unit-measure': 'pc_ent'},
    {'indicator': 'actspeed', 'breakdown': 'FTTX', 'unit-measure': 'pc_nomspeed'},
    {'indicator': 'h_broad', 'breakdown': 'hh_total', 'unit-measure': 'pc_hh'},
    {'indicator': 'h_iacc', 'breakdown': 'hh_total', 'unit-measure': 'pc_hh'},
    {'indicator': 'i_blt12', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_blt12', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_ilt12'},
    {'indicator': 'i_bfeu', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_bfeu', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_ilt12'},
    {'indicator': 'i_iusell', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_bgoodo', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_ilt12'},
    {'indicator': 'i_iugov12', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_igov12rt', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_cprg', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_cweb', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_csk_ge_me', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_isk_ge_me', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_iuif', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_iunw', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_iugm', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_iubk', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_iuupl', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_ihif', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_iujob', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_iuolc', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_iueduif', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_iugov', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_igovrt', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_iusnet', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_iuvote', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'I_IUMAPP', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'I_IUPH1', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_iuse', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_iday', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_iumc', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_iux', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_iu3g', 'breakdown': 'ind_total', 'unit-measure': 'pc_ind'},
    {'indicator': 'Price_Internet_Fixed_Tel', 'breakdown': 'offer_8_12_Mbps', 'unit-measure': 'median_euro_PPP'},
    {'indicator': 'Price_Internet_Fixed_Tel_TV', 'breakdown': 'offer_8_12_Mbps', 'unit-measure': 'median_euro_PPP'},
    {'indicator': 'Price_Internet_only', 'breakdown': 'offer_8_12_Mbps', 'unit-measure': 'median_euro_PPP'},
    {'indicator': 'FP7ICT_EC_funding', 'breakdown': 'orgclass_hesrec', 'unit-measure': 'pc_FP7ICT_EC_funding'},
    {'indicator': 'FP7ICT_EC_funding', 'breakdown': 'orgclass_le', 'unit-measure': 'pc_FP7ICT_EC_funding'},
    {'indicator': 'FP7ICT_EC_funding', 'breakdown': 'orgclass_nil', 'unit-measure': 'pc_FP7ICT_EC_funding'},
    {'indicator': 'FP7ICT_EC_funding', 'breakdown': 'orgclass_sme', 'unit-measure': 'pc_FP7ICT_EC_funding'},
    {'indicator': 'FP7ICT_cofin', 'breakdown': 'orgclass_sme', 'unit-measure': 'pc_total_cost'},
    {'indicator': 'FP7ICT_afxp', 'breakdown': 'orgclass_sme', 'unit-measure': 'euro'},
    {'indicator': 'FP7ICT_EC_funding', 'breakdown': 'orgclass_total', 'unit-measure': 'euro_x_hab'},
    {'indicator': 'FP7ICT_EC_funding', 'breakdown': 'orgclass_total', 'unit-measure': 'euro_x_million_of_GDP'},
    {'indicator': 'FP7ICT_newENTRY', 'breakdown': 'orgclass_total', 'unit-measure': 'pc_organisations'},
    {'indicator': 'FP7ICT_cofin', 'breakdown': 'orgclass_total', 'unit-measure': 'pc_total_cost'},
    {'indicator': 'FP7ICT_afxp', 'breakdown': 'orgclass_total', 'unit-measure': 'euro'},
    {'indicator': 'i_iuse', 'breakdown': 'rf_ge1', 'unit-measure': 'pc_ind'},
    {'indicator': 'bb_fcov', 'breakdown': 'rural_pop', 'unit-measure': 'pc_rural_pop'},
    {'indicator': 'i_cisk_sfjobx', 'breakdown': 'sal_self_fam', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_cisk_sfjob', 'breakdown': 'sal_self_fam', 'unit-measure': 'pc_ind'},
    {'indicator': 'FOA_cit', 'breakdown': 'total', 'unit-measure': 'pc_pub_serv_for_citizen'},
    {'indicator': 'FOA_ent', 'breakdown': 'total', 'unit-measure': 'pc_pub_serv_for_ent'},
    {'indicator': 'mob_roam', 'breakdown': 'total', 'unit-measure': 'eurocent_minute'},
    {'indicator': 'gbaord_ict', 'breakdown': 'total', 'unit-measure': 'pc_gbaord'},
    {'indicator': 'bb_penet', 'breakdown': 'TOTAL_FBB', 'unit-measure': 'subs_per_100_pop'},
    {'indicator': 'bb_ne', 'breakdown': 'TOTAL_FBB', 'unit-measure': 'pc_lines'},
    {'indicator': 'bb_dsl', 'breakdown': 'TOTAL_FBB', 'unit-measure': 'pc_lines'},
    {'indicator': 'bb_speed2', 'breakdown': 'TOTAL_FBB', 'unit-measure': 'pc_lines'},
    {'indicator': 'bb_speed10', 'breakdown': 'TOTAL_FBB', 'unit-measure': 'pc_lines'},
    {'indicator': 'bb_speed30', 'breakdown': 'TOTAL_FBB', 'unit-measure': 'pc_lines'},
    {'indicator': 'bb_speed100', 'breakdown': 'TOTAL_FBB', 'unit-measure': 'pc_lines'},
    {'indicator': 'mbb_penet', 'breakdown': 'TOTAL_MBB', 'unit-measure': 'subs_per_100_pop'},
    {'indicator': 'mob_penet', 'breakdown': 'TOTAL_MOB', 'unit-measure': 'subs_per_100_pop'},
    {'indicator': 'mob_ms', 'breakdown': 'total_mob', 'unit-measure': 'pc_subs'},
    {'indicator': 'mob_arpu', 'breakdown': 'total_mob', 'unit-measure': 'euro'},
    {'indicator': 'mob_arpm', 'breakdown': 'total_mob', 'unit-measure': 'euro'},
    {'indicator': 'bb_fcov', 'breakdown': 'total_pop', 'unit-measure': 'pc_pop'},
    {'indicator': 'mbb_3gcov', 'breakdown': 'total_pop', 'unit-measure': 'pc_pop'},
    {'indicator': 'bb_scov', 'breakdown': 'TOTAL_POPHH', 'unit-measure': 'pc_hh_all'},
    {'indicator': 'bb_ngacov', 'breakdown': 'TOTAL_POPHH', 'unit-measure': 'pc_hh_all'},
    {'indicator': 'mbb_hspacov', 'breakdown': 'TOTAL_POPHH', 'unit-measure': 'pc_hh_all'},
    {'indicator': 'tel_invrev', 'breakdown': 'total_telecom', 'unit-measure': 'pc_revenue'},
    {'indicator': 'actspeed', 'breakdown': 'xDSL', 'unit-measure': 'pc_nomspeed'},
    {'indicator': 'i_skedu', 'breakdown': 'y16_24', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_ia12ave', 'breakdown': 'y16_24', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_skedu', 'breakdown': 'y25_54', 'unit-measure': 'pc_ind'},
    {'indicator': 'i_ia12ave', 'breakdown': 'y25_54', 'unit-measure': 'pc_ind_iu3'},
    {'indicator': 'i_ia12ave', 'breakdown': 'y55_74', 'unit-measure': 'pc_ind_iu3'}
]
